# Generated by Django 4.1.7 on 2023-04-08 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_task_image_alter_proyecto_id_alter_task_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='important',
            field=models.BooleanField(default=False, verbose_name='Importancía de la tarea'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.proyecto', verbose_name='Proyecto al que pertenece'),
        ),
    ]
