# Generated by Django 4.1.7 on 2023-04-08 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_alter_task_important_alter_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario al que pertenece'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
